services:
  the-myspace:
    container_name: the-myspace
    image: chiefmikey/the-myspace:latest
    networks:
      - mikl-net
    ports:
      - 80:8080
    healthcheck:
      test: node healthcheck.js
      interval: 10s
      timeout: 10s
      retries: 10

  cloudyman:
    container_name: cloudyman
    image: chiefmikey/cloudyman:latest
    depends_on:
      name-generator_client:
        condition: service_healthy
    networks:
      - mikl-net
    ports:
      - 3002:3002
    healthcheck:
      test: node healthcheck.js
      interval: 10s
      timeout: 10s
      retries: 10

  name-generator_client:
    container_name: name-generator_client
    image: chiefmikey/name-generator:latest
    depends_on:
      name-generator_db:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - mikl-net
    ports:
      - 3001:3001
    healthcheck:
      test: node healthcheck.js
      interval: 10s
      timeout: 10s
      retries: 10

  name-generator_db:
    container_name: name-generator_db
    image: chiefmikey/cassandra:latest
    depends_on:
      the-myspace:
        condition: service_healthy
    networks:
      - mikl-net
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test:
        cd /opt/cassandra && su -s /bin/bash -c 'bin/cqlsh --debug' cassandra
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  cassandra-data:

networks:
  mikl-net:
