services:
  proxy:
    container_name: proxy
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock

  the-myspace:
    container_name: the-myspace
    image: chiefmikey/the-myspace:latest
    networks:
      - mikl-net
    ports:
      - 3000:3000
    healthcheck:
      test: node healthcheck.js
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
    - "VIRTUAL_HOST=themyspace.org,www.themyspace.org"

  tommyman:
    container_name: tommyman
    image: chiefmikey/tommyman:latest
    depends_on:
      the-myspace:
        condition: service_healthy
    networks:
      - mikl-net
    ports:
      - 3003:3003
    healthcheck:
      test: node healthcheck.js
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - "VIRTUAL_HOST=hullowurld.com,www.hullowurld.com,tommyman.itsacloudynight.com"

  cloudyman:
    container_name: cloudyman
    image: chiefmikey/cloudyman:latest
    depends_on:
      the-myspace:
        condition: service_healthy
    networks:
      - mikl-net
    ports:
      - 3002:3002
    healthcheck:
      test: node healthcheck.js
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
    - "VIRTUAL_HOST=itsacloudynight.com,www.itsacloudynight.com,cloudyman.itsacloudynight.com"

  name-generator_client:
    container_name: name-generator_client
    image: chiefmikey/name-generator:latest
    depends_on:
      name-generator_db:
        condition: service_healthy
    networks:
      - mikl-net
    ports:
      - 3001:3001
    healthcheck:
      test: node healthcheck.js
      interval: 10s
      timeout: 10s
      retries: 10
  environment:
  - "VIRTUAL_HOST=name.themyspace.org,www.name.themyspace.org"

  name-generator_db:
    container_name: name-generator_db
    image: chiefmikey/alpine-cassandra:latest
    depends_on:
      the-myspace:
        condition: service_healthy
    networks:
      - mikl-net
    volumes:
      - cassandra-data:/var/lib/cassandra
    healthcheck:
      test:
        cd /opt/cassandra && su -s /bin/bash -c 'bin/cqlsh --debug' cassandra
      interval: 10s
      timeout: 10s
      retries: 10

volumes:
  cassandra-data:

networks:
  mikl-net:
