name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
env:
  ANIMAL_KEY: ${{ secrets.ANIMAL_KEY }}
  ANIMAL_SECRET: ${{ secrets.ANIMAL_SECRET }}
  WEATHER: ${{ secrets.WEATHER }}
  NODE_ENV: production
jobs:
  continuous-integration:
    environment:
      name: mikl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set secrets
        run: |
          docker secret create \
            --label ANIMAL_KEY=${{ secrets.ANIMAL_KEY }} \
            --label ANIMAL_SECRET=${{ secrets.ANIMAL_SECRET }} \
            --label WEATHER=${{ secrets.WEATHER }} \
            --label NODE_ENV=production
      - name: Build Application
        run: docker-compose up -d
  continuous-deployment:
    environment:
      name: mikl
      url: https://github.com
    runs-on: ubuntu-latest
    needs: [continuous-integration]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # if you have/need it
          aws-region: us-east-2
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment --ignore-application-stop-failures \
            --application-name mikl \
            --deployment-group-name mikld \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
